package com.kutoru.mikunotes.logic

const val DOWNLOAD_NOTIFICATION_CHANNEL_ID = "DOWNLOAD_NOTIFICATION"
const val FILE_NOTIFICATION_BROADCAST = "com.kutoru.mikunotes.FILE_NOTIFICATION_BROADCAST"
const val FILE_NOTIFICATION_IDENTIFIER = "FILE_NOTIFICATION_IDENTIFIER"
const val PREFERENCE_FILE_KEY = "PREFERENCE_FILE_KEY"
const val LAUNCHED_LOGIN_FROM_ERROR = "LAUNCHED_LOGIN_FROM_ERROR"
const val SELECTED_NOTE = "SELECTED_NOTE"
const val CREATE_NEW_NOTE = "CREATE_NEW_NOTE"
const val RECYCLER_VIEW_FILE_COLUMNS = 2
const val ANIMATION_TRANSITION_TIME = 200

// persistent storage keys
const val ACCESS_TOKEN_STORAGE_KEY = "ACCESS_TOKEN_COOKIE_KEY"
const val REFRESH_TOKEN_STORAGE_KEY = "REFRESH_TOKEN_COOKIE_KEY"
const val EMAIL_STORAGE_KEY = "EMAIL_STORAGE_KEY"
const val DOMAIN_STORAGE_KEY = "DOMAIN_STORAGE_KEY"
const val PORT_STORAGE_KEY = "PORT_STORAGE_KEY"
const val IS_SECURE_STORAGE_KEY = "IS_SECURE_STORAGE_KEY"
