package com.kutoru.mikunotes.logic

const val DOWNLOAD_NOTIFICATION_CHANNEL_ID = "DOWNLOAD_NOTIFICATION"
const val PREFERENCE_FILE_KEY = "PREFERENCE_FILE_KEY"
const val ACCESS_TOKEN_COOKIE_KEY = "ACCESS_TOKEN_COOKIE_KEY"
const val REFRESH_TOKEN_COOKIE_KEY = "REFRESH_TOKEN_COOKIE_KEY"
const val API_DOMAIN = "192.168.1.12"
const val API_URL = "http://$API_DOMAIN:3030"
