package com.kutoru.mikunotes.logic

const val DOWNLOAD_NOTIFICATION_CHANNEL_ID = "DOWNLOAD_NOTIFICATION"
const val PREFERENCE_FILE_KEY = "PREFERENCE_FILE_KEY"

// persistent storage keys
const val ACCESS_TOKEN_STORAGE_KEY = "ACCESS_TOKEN_COOKIE_KEY"
const val REFRESH_TOKEN_STORAGE_KEY = "REFRESH_TOKEN_COOKIE_KEY"
const val EMAIL_STORAGE_KEY = "EMAIL_STORAGE_KEY"
const val DOMAIN_STORAGE_KEY = "DOMAIN_STORAGE_KEY"
const val PORT_STORAGE_KEY = "PORT_STORAGE_KEY"
const val IS_SECURE_STORAGE_KEY = "IS_SECURE_STORAGE_KEY"
