name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    #- name: Setup jdk
    #  uses: actions/setup-java@v1
    #  with:
    #    java-version: 17
    #- name: Make gradle executable
    #  run: chmod +x ./gradlew
    #- name: Build apk
    #  run: ./gradlew assembleRelease

    - name: Upload apk
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
          files: ./*.md
