name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: fix git
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    #- name: setup jdk
    #  uses: actions/setup-java@v1
    #  with:
    #    java-version: 17
    #- name: make gradle executable
    #  run: chmod +x ./gradlew
    #- name: build apk
    #  run: ./gradlew assembleRelease
    - name: release apk
      uses: kutoru/action-releaseapk@84c14471a8d9fa6027bb29aaf10a49a3e443c45f
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
