name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    #- name: Setup jdk
    #  uses: actions/setup-java@v1
    #  with:
    #    java-version: 17
    #- name: Make gradle executable
    #  run: chmod +x ./gradlew
    #- name: Build apk
    #  run: ./gradlew assembleRelease
    - name: Release apk
      uses: kutoru/action-releaseapk@c15d873257579eb3deec722d38b5dfae27c4df76
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
