name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make decrypt script executable
      run: chmod +x ./decrypt_keystore.sh
    - name: Change decrypt script CR format
      run: sed -i -e 's/\r$//' ./decrypt_keystore.sh
    - name: Decrypt keystore file
      run: ./decrypt_keystore.sh
      env:
        KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build APK
      run: ./gradlew assembleRelease
        -Pandroid.injected.signing.store.file=$HOME/secrets/androiduser.keystore
        -Pandroid.injected.signing.store.password=${{ secrets.STORE_PASSWORD }}
        -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }}
        -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
          files: ./app/build/outputs/apk/release/*-release.apk
